import time
time.sleep(2)
print("Welcome to my first game!")
time.sleep(1)
print("All you have to do is hold enter!")
time.sleep(2)
print("STOP AT 30 OR RESULTS.TXT WILL BE FILLED!!!")
time.sleep(3)
print("3")
time.sleep(1)
print("2")
time.sleep(1)
print("1")
time.sleep(1)

input(1)
input(2)
input(3)
input(4)
input(5)
input(6)
input(7)
input(8)
input(9)
input(10)
input(11)
input(12)
input(13)
print("CHECKPOINT! YOU WILL NEED TO STOP SOON!")
input(14)
input(15)
input(16)
input(17)
input(18)
input(19)
input(20)
input(21)
input(22)
input(23)
input(24)
input(25)
input(26)
input(27)
input(28)
input(29)
input(30)
print("STOP!")
print("NOO! LOOK AT RESULTS.TXT!!!")

f = open("Results.txt", "w")
f.write("YOU FAILED TO STOP, START OVER!")
f.close()
